# Generated by Django 5.2 on 2025-04-10 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quora_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='title',
            new_name='post_question',
        ),
    ]
